### ISSUE TITLE
[QUESTION] Perlukah menambahkan informasi 'umur' diskon (berlaku sampai kapan)?

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-2.0#115]
![question-fe-1](https://cloud.githubusercontent.com/assets/5895063/17550221/2da82a4a-5f1e-11e6-8ce4-5d985e2f8c7b.png)

**Comment by erickmo** [comment]
Boleh, terutama untuk yg diskonnya < n days. Jadi kita beri efek kepepet buat user

Best regards,
Erick Mo
