### ISSUE TITLE
[QUESTION] Perlukah membuat customer mengerti informasi point balin ? 

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-2.0#117]
*cust yang di test tidak paham cara kerja point balin, sehingga fokus belanja hanya pada produk, diskon / 'sale', harga asli, homepage

**Comment by erickmo** [comment]
Perlu tapi masih blm perlu kita expose dulu sih

Best regards,
Erick Mo

**Comment by chelsymooy** [comment]
noted, sir
