### ISSUE TITLE
[Balin.id] Uppercase dan Lowercase untuk referral code

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-2.0#55]
![lowercase](https://cloud.githubusercontent.com/assets/5895063/12666154/b5fc44b8-c670-11e5-9bfc-10d59ccf7a27.png)
![uppercase lowercase](https://cloud.githubusercontent.com/assets/5895063/12666157/b9a66562-c670-11e5-839a-178a87dd4b85.png)

**Comment by agilma** [comment]
https://github.com/ThunderID/BALIN-2.0/commit/265b3dd45c2ba62c7c314551f9da740fbb077092
