### ISSUE TITLE
Create HasNameTrait

### ISSUE THREAD

**Issue by erickmo** [ThunderID/BALIN-2.0#6]
# Description

To create a trait for model that has name field.
# Requirement:
- model that use this trait must specify the field use as the name field, i.e. title
# Features:
- name field does not have to be "name". It can be "title" or something else
- searchable by name using wildstring, i.e. _search_ akan mencari %search%, tetapi perlu diingat untuk pencarian *\* diabaikan dan tidak dimasukkan ke dalam query karena hanya akan menambah load query
# To do
- [ ] bootHasNameTrait
- [ ] scopes
  - [ ] scopeName($q, $v) - implement "*" for wildstring search
- [ ] mutator
  - [ ] setNameAttribute()
- [ ] accessor
  - [ ] getNameAttribute()
# Observer
- none

**Comment by chelsymooy** [comment]
Move to api
