### ISSUE TITLE
PublishableTrait

### ISSUE THREAD

**Issue by erickmo** [ThunderID/BALIN-2.0#7]
# Description

To create a trait for model that is publishable
# Requirement:
- model that use this trait must specify the field as the source to generate slug, i.e. title
- model must have slug & published_at field
# Features:
- searchable by slug using wildstring, i.e. _search_ akan mencari %search%, tetapi perlu diingat untuk pencarian *\* diabaikan dan tidak dimasukkan ke dalam query karena hanya akan menambah load query
# To do
- [ ] bootPublishableTrait
- [ ] scopes
  - [ ] scopePublished($q, $until_date = 'now') 
  - [ ] scopeUpcoming($q)
  - [ ] scopeDraft($q)
  - [ ] scopeSlug($q)
  - [ ] scopeSortLatestPublished()
  - [ ] scopeSortOldestPublished()
- [ ] accessor
  - [ ] getIsPublishedAttribute()
  - [ ] getAlreadyPublishedAttribute()
  - [ ] getIsUpcomingAttribute()
# Observer
- #8 Publishable Observer

**Comment by chelsymooy** [comment]
Move to api
