### ISSUE TITLE
[Balin.id] Product Index

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-2.0#71]
- [x] Grid not friendly
- [x] sm/xs image not full
- [x] filter not good appearance
  ![produk-md](https://cloud.githubusercontent.com/assets/5895063/12719394/5dccbdf4-c927-11e5-9099-9ba7fb723995.png)
  ![produk-sm](https://cloud.githubusercontent.com/assets/5895063/12719410/71524f6a-c927-11e5-97f5-9f90243f7c3d.png)
  ![filter-md](https://cloud.githubusercontent.com/assets/5895063/12719449/aa6db5d2-c927-11e5-8921-c789457ed578.png)
  ![filter-sm2](https://cloud.githubusercontent.com/assets/5895063/12719456/aed5f4d6-c927-11e5-8866-3f06998f4539.png)

**Comment by agilma** [comment]
https://github.com/ThunderID/BALIN-2.0/commit/4503dfb2fbb77b439a46bca80433ecea9661b4a2
