### ISSUE TITLE
[User Story] As a user, i want to add extra notes for my purchase so that I can send the purchase as a gift to someone

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/BALIN-2.0#97]
- [x] We need provide db record for custom card and package 
- [x] We interface to write down custom card and marked as gitf

**Comment by agilma** [comment]
https://github.com/ThunderID/BALIN-2.0/commit/a6c582a9e1243e0838e4b0e7d0489b36f5672661

**Comment by chelsymooy** [comment]
Product extension
